export const FETCH_REQUESTED = 'cms/FETCH_REQUESTED';
export const FETCH_REQUESTED_SUCCEEDED = 'cms/FETCH_REQUESTED_SUCCEEDED';
export const FETCH_REQUESTED_FAILED = 'cms/FETCH_REQUESTED_FAILED';

export const FETCH_ONE_REQUESTED = 'cms/FETCH_ONE_REQUESTED';
export const FETCH_ONE_SUCCEEDED = 'cms/FETCH_ONE_SUCCEEDED';
export const FETCH_ONE_FAILED = 'cms/FETCH_ONE_FAILED';