export const FETCH_REQUESTED = 'currencies/FETCH_REQUESTED';
export const FETCH_REQUESTED_SUCCEEDED = 'currencies/FETCH_REQUESTED_SUCCEEDED';
export const FETCH_REQUESTED_FAILED = 'currencies/FETCH_REQUESTED_FAILED';