export const FETCH_CART_DATA = 'FETCH_CART_DATA'
export const CART_DATA_REQUEST = 'CART_DATA_REQUEST'
export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST'
export const USER_LOGOUT = 'USER_LOGOUT'