export const FETCH_CART_DATA = 'FETCH_CART_DATA'
export const CART_DATA_REQUEST = 'CART_DATA_REQUEST'
export const CART_ITEM_DATA_REQUEST = 'CART_ITEM_DATA_REQUEST'
export const USER_LOGOUT = 'USER_LOGOUT'