export const FETCH_REQUESTED = 'stores/FETCH_REQUESTED';
export const FETCH_REQUESTED_SUCCEEDED = 'stores/FETCH_REQUESTED_SUCCEEDED';
export const FETCH_REQUESTED_FAILED = 'stores/FETCH_REQUESTED_FAILED';