export const ADD_TO_CART_REQUESTED = 'cart/ADD_TO_CART_REQUESTED';
export const ADD_TO_CART_REQUESTED_SUCCEEDED = 'cart/ADD_TO_CART_REQUESTED_SUCCEEDED';
export const ADD_TO_CART_REQUESTED_FAILED = 'cart/ADD_TO_CART_REQUESTED_FAILED';

export const CREATE_CART_REQUESTED = 'cart/CREATE_CART_REQUESTED';
export const CREATE_CART_REQUESTED_SUCCEEDED = 'cart/CREATE_CART_REQUESTED_SUCCEEDED';
export const CREATE_CART_REQUESTED_FAILED = 'cart/CREATE_CART_REQUESTED_FAILED';