export const LOGIN_REQUESTED = 'cart/LOGIN_REQUESTED';
export const LOGIN_REQUESTED_SUCCEEDED = 'cart/LOGIN_REQUESTED_SUCCEEDED';
export const LOGIN_REQUESTED_FAILED = 'cart/LOGIN_REQUESTED_FAILED';