export const ADD_TO_CART_REQUESTED = 'cart/ADD_TO_CART_REQUESTED';
export const ADD_TO_CART_REQUESTED_SUCCEEDED = 'cart/ADD_TO_CART_REQUESTED_SUCCEEDED';
export const ADD_TO_CART_REQUESTED_FAILED = 'cart/ADD_TO_CART_REQUESTED_FAILED';

export const GET_CART_ID_REQUESTED = 'cart/GET_CART_ID_REQUESTED';
export const GET_CART_ID_REQUESTED_SUCCEEDED = 'cart/GET_CART_ID_REQUESTED_SUCCEEDED';
export const GET_CART_ID_REQUESTED_FAILED = 'cart/GET_CART_ID_REQUESTED_FAILED';

export const ADD_CART_ITEM_REQUESTED = 'cart/ADD_CART_ITEM_REQUESTED';
export const ADD_CART_ITEM_REQUESTED_SUCCEEDED = 'cart/ADD_CART_ITEM_REQUESTED_SUCCEEDED';
export const ADD_CART_ITEM_REQUESTED_FAILED = 'cart/ADD_CART_ITEM_REQUESTED_FAILED';