export const FETCH_REQUESTED = 'productlist/FETCH_REQUESTED';
export const FETCH_REQUESTED_SUCCEEDED = 'productlist/FETCH_REQUESTED_SUCCEEDED';
export const FETCH_REQUESTED_FAILED = 'productlist/FETCH_REQUESTED_FAILED';