export const FETCH_FEATURES_REQUESTED = 'product/FETCH_FEATURES_REQUESTED';
export const FETCH_FEATURES_REQUESTED_SUCCEEDED = 'product/FETCH_FEATURES_REQUESTED_SUCCEEDED';
export const FETCH_FEATURES_REQUESTED_FAILED = 'product/FETCH_FEATURES_REQUESTED_FAILED';