export const FETCH_FEATURES_REQUESTED = 'product/FETCH_FEATURES_REQUESTED';
export const FETCH_FEATURES_REQUESTED_SUCCEEDED = 'product/FETCH_FEATURES_REQUESTED_SUCCEEDED';
export const FETCH_FEATURES_REQUESTED_FAILED = 'product/FETCH_FEATURES_REQUESTED_FAILED';

export const FETCH_BUNDLE_REQUESTED = 'product/FETCH_BUNDLE_REQUESTED';
export const FETCH_BUNDLE_REQUESTED_SUCCEEDED = 'product/FETCH_BUNDLE_REQUESTED_SUCCEEDED';
export const FETCH_BUNDLE_REQUESTED_FAILED = 'product/FETCH_BUNDLE_REQUESTED_FAILED';


export const FETCH_ACCESSORIES_REQUESTED = 'product/FETCH_ACCESSORIES_REQUESTED';
export const FETCH_ACCESSORIES_REQUESTED_SUCCEEDED = 'product/FETCH_ACCESSORIES_REQUESTED_SUCCEEDED';
export const FETCH_ACCESSORIES_REQUESTED_FAILED = 'product/FETCH_ACCESSORIES_REQUESTED_FAILED';