export const FETCH_COMBINATION_REQUESTED = 'combinations/FETCH_COMBINATION_REQUESTED';
export const FETCH_COMBINATION_SUCCEEDED = 'combinations/FETCH_COMBINATION_SUCCEEDED';
export const FETCH_COMBINATION_FAILED = 'combinations/FETCH_COMBINATION_FAILED';

export const FETCH_OPTION_REQUESTED = 'combinations/FETCH_OPTION_REQUESTED';
export const FETCH_OPTION_SUCCEEDED = 'combinations/FETCH_OPTION_SUCCEEDED';
export const FETCH_OPTION_FAILED = 'combinations/FETCH_OPTION_FAILED';

export const FETCH_ALL_REQUESTED = 'combinations/FETCH_ALL_REQUESTED';
export const FETCH_ALL_SUCCEEDED = 'combinations/FETCH_ALL_SUCCEEDED';
export const FETCH_ALL_FAILED = 'combinations/FETCH_ALL_FAILED';

export const FETCH_PRODUCT_REQUESTED = 'combinations/FETCH_PRODUCT_REQUESTED';
export const FETCH_PRODUCT_SUCCEEDED = 'combinations/FETCH_PRODUCT_SUCCEEDED';
export const FETCH_PRODUCT_FAILED = 'combinations/FETCH_PRODUCT_FAILED';