export const FETCH_REQUESTED = 'user/FETCH_REQUESTED';
export const FETCH_REQUESTED_SUCCEEDED = 'user/FETCH_REQUESTED_SUCCEEDED';
export const FETCH_REQUESTED_FAILED = 'user/FETCH_REQUESTED_FAILED';