export const FETCH_LOGIN_REQUESTED = 'user/FETCH_LOGIN_REQUESTED';
export const FETCH_LOGIN_REQUESTED_SUCCEEDED = 'user/FETCH_LOGIN_REQUESTED_SUCCEEDED';
export const FETCH_LOGIN_REQUESTED_FAILED = 'user/FETCH_LOGIN_REQUESTED_FAILED';


export const FETCH_REGISTRATION_REQUESTED = 'user/FETCH_REGISTRATION_REQUESTED';
export const FETCH_REGISTRATION_REQUESTED_SUCCEEDED = 'user/FETCH_REGISTRATION_REQUESTED_SUCCEEDED';
export const FETCH_REGISTRATION_REQUESTED_FAILED = 'user/FETCH_RE GISTRATION_REQUESTED_FAILED';

export const RESET_ERROR = 'user/RESET_ERROR';

export const FETCH_LOGOUT_REQUESTED  = 'user/FETCH_LOGOUT_REQUESTED';
export const FETCH_LOGOUT_REQUESTED_SUCCEEDED  = 'user/FETCH_LOGOUT_REQUESTED_SUCCEEDED';
export const FETCH_LOGOUT_REQUESTED_FAILED  = 'user/FETCH_LOGOUT_REQUESTED_FAILED';
