export const FETCH_REQUESTED = 'user/FETCH_REQUESTED';
export const FETCH_REQUESTED_SUCCEEDED = 'user/FETCH_REQUESTED_SUCCEEDED';
export const FETCH_REQUESTED_FAILED = 'user/FETCH_REQUESTED_FAILED';


export const FETCH_REGISTRATION_REQUESTED = 'user/FETCH_REGISTRATION_REQUESTED';
export const FETCH_REGISTRATION_REQUESTED_SUCCEEDED = 'user/FETCH_REGISTRATION_REQUESTED_SUCCEEDED';
export const FETCH_REGISTRATION_REQUESTED_FAILED = 'user/FETCH_RE GISTRATION_REQUESTED_FAILED';

export const RESET_ERROR = 'user/RESET_ERROR';
