export const FETCH_REQUESTED = 'category/FETCH_REQUESTED';
export const FETCH_REQUESTED_SUCCEEDED = 'category/FETCH_REQUESTED_SUCCEEDED';
export const FETCH_REQUESTED_FAILED = 'category/FETCH_REQUESTED_FAILED';

export const FETCH_ONE_REQUESTED = 'category/FETCH_ONE_REQUESTED';
export const FETCH_ONE_SUCCEEDED = 'category/FETCH_ONE_SUCCEEDED';
export const FETCH_ONE_FAILED = 'category/FETCH_ONE_FAILED';

export const FETCH_SUB_CAT_REQUESTED = 'category/FETCH_SUB_CAT_REQUESTED';
export const FETCH_SUB_CAT_SUCCEEDED = 'category/FETCH_SUB_CAT_SUCCEEDED';
export const FETCH_SUB_CAT_FAILED = 'category/FETCH_SUB_CAT_FAILED';