export const FETCH_REQUESTED = 'category/FETCH_REQUESTED';
export const FETCH_REQUESTED_SUCCEEDED = 'category/FETCH_REQUESTED_SUCCEEDED';
export const FETCH_REQUESTED_FAILED = 'category/FETCH_REQUESTED_FAILED';