export const FETCH_REQUESTED = 'contacts/FETCH_REQUESTED';
export const FETCH_REQUESTED_SUCCEEDED = 'contacts/FETCH_REQUESTED_SUCCEEDED';
export const FETCH_REQUESTED_FAILED = 'contacts/FETCH_REQUESTED_FAILED';
